### ISSUE TITLE
new query language

### ISSUE THREAD

**Issue by nicholasdelrio** [nicholasdelrio/visko#25]
VISUALIZE x AS Y IN Z
WHERE
    FORMAT = A
    AND TYPE = B
    AND param1 = C
    AND param2 = D ...

**Comment by paulopinheiro1234** [comment]
VISUALIZE (X1,...,Xn) AS Y IN Z
WHERE
    FORMAT = A
    AND TYPE = B
    AND param1 = C
    AND param2 = D ...

And Y can be, for instance, a xyplot_comparison

---

Paulo Pinheiro da Silva
Senior Research Scientist
Pacific Northwest National Laboratory
